#!/bin/bash

# Setup script for TrustWrapper Eliza Plugin GitHub repository
# Run this from the trustwrapper-eliza-plugin directory

echo "🚀 Setting up TrustWrapper Eliza Plugin GitHub repository..."
echo ""

# Repository details
REPO_NAME="trustwrapper-eliza-plugin"
REPO_OWNER="lamassu-labs"
REPO_DESCRIPTION="Universal AI verification plugin for Eliza framework - Build trustworthy AI agents with zero-knowledge proofs"

echo "📋 Prerequisites:"
echo "   1. Create repository at: https://github.com/new"
echo "   2. Repository name: $REPO_NAME"
echo "   3. Owner: $REPO_OWNER (create org if needed)"
echo "   4. Description: $REPO_DESCRIPTION"
echo "   5. Public repository"
echo "   6. DO NOT initialize with README/gitignore/license"
echo ""

echo "🔧 Once repository is created, run these commands:"
echo ""
echo "cd /Users/eladm/Projects/trustwrapper-eliza-plugin"
echo ""
echo "# Add remote origin"
echo "git remote add origin https://github.com/$REPO_OWNER/$REPO_NAME.git"
echo ""
echo "# Verify remote"
echo "git remote -v"
echo ""
echo "# Push to GitHub"
echo "git push -u origin main"
echo ""
echo "# Set repository topics"
echo "gh repo edit $REPO_OWNER/$REPO_NAME --add-topic eliza-plugin,ai-agents,verification,zero-knowledge-proof,trustwrapper,typescript,blockchain"
echo ""
echo "# Configure repository settings"
echo "gh repo edit $REPO_OWNER/$REPO_NAME --description \"$REPO_DESCRIPTION\""
echo "gh repo edit $REPO_OWNER/$REPO_NAME --homepage \"https://trustwrapper.io\""
echo ""
echo "🔐 For npm publishing:"
echo "   1. Create npm account at: https://www.npmjs.com/signup"
echo "   2. Generate access token: https://www.npmjs.com/settings/YOUR_USERNAME/tokens"
echo "   3. Add NPM_TOKEN to GitHub secrets: https://github.com/$REPO_OWNER/$REPO_NAME/settings/secrets/actions"
echo ""
echo "📦 Initial npm publish (one-time):"
echo "npm login"
echo "npm publish --access public"
echo ""
echo "✅ After setup, the CI/CD will handle:"
echo "   - Automated testing on PRs"
echo "   - Automated npm publishing on releases"
echo "   - Code coverage reporting"
