steps:
  # Build Treasury Monitor Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-f', 'src/treasury_monitor/Dockerfile', '-t', 'gcr.io/$PROJECT_ID/treasury-monitor:latest', '.']

  # Push the image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/treasury-monitor:latest']

  # Deploy to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'gcloud'
    args:
      - 'run'
      - 'deploy'
      - 'treasury-monitor'
      - '--image=gcr.io/$PROJECT_ID/treasury-monitor:latest'
      - '--platform=managed'
      - '--region=us-central1'
      - '--allow-unauthenticated'
      - '--port=8080'
      - '--memory=2Gi'
      - '--cpu=1'
      - '--min-instances=0'
      - '--max-instances=10'
      - '--set-env-vars=DEPLOYMENT_ENV=production'
      - '--set-env-vars=PYTHONPATH=/app'

options:
  logging: CLOUD_LOGGING_ONLY
  machineType: 'E2_HIGHCPU_8'

timeout: '1200s'
