# Treasury Monitor Agent - Enterprise Cloud Build Configuration
# ENTERPRISE STANDARD: Following tokenhunter-457310 deployment patterns
steps:
  # Build the Treasury Monitor Docker image using enterprise structure
  - name: 'gcr.io/cloud-builders/docker'
    args: [
      'build',
      '-t', 'gcr.io/$PROJECT_ID/treasury-monitor-agent:latest',
      '-t', 'gcr.io/$PROJECT_ID/treasury-monitor-agent:$BUILD_ID',
      '-f', 'src/treasury_monitor/Dockerfile',
      '.'
    ]

  # Push the Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args: [
      'push', 'gcr.io/$PROJECT_ID/treasury-monitor-agent:latest'
    ]

  # Deploy to Cloud Run
  - name: 'gcr.io/cloud-builders/gcloud'
    args: [
      'run', 'deploy', 'treasury-monitor-agent',
      '--image', 'gcr.io/$PROJECT_ID/treasury-monitor-agent:latest',
      '--region', 'us-central1',
      '--platform', 'managed',
      '--memory', '2Gi',
      '--cpu', '1',
      '--max-instances', '10',
      '--min-instances', '1',
      '--allow-unauthenticated',
      '--set-env-vars', 'PROJECT_ID=$PROJECT_ID,REGION=us-central1,KOIOS_FALLBACK_ENABLED=true,DEPLOYMENT_ENV=production'
    ]

# Service account with necessary permissions
serviceAccount: 'projects/$PROJECT_ID/serviceAccounts/chatbot-api-sa@tokenhunter-457310.iam.gserviceaccount.com'

options:
  # Use high-performance machine for faster builds
  machineType: 'E2_HIGHCPU_8'

  # Enable detailed logging
  logging: CLOUD_LOGGING_ONLY

# Timeout for the build
timeout: '1200s'
